---
plugins:
  - rubocop-factory_bot
  - rubocop-minitest
  - rubocop-rake
AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/schema.rb'
    - 'bin/rails'
    - 'bin/rake'
    - '**/*.rake'
    - 'storage/**/*'
    - '**/shims/**'
    - '**.py'
    - 'test/dummy/**/*'
  NewCops: enable

Layout/EndOfLine:
  EnforcedStyle: lf
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/EmptyClass:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/MissingSuper:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/PercentStringArray:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Exclude:
    - "test/**/**/*"
    - "app/models/barion/payment.rb"
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'test/**/**/*'
Minitest/MultipleAssertions:
  Enabled: true
  Max: 40
Style/AccessorGrouping:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/RescueStandardError:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/SymbolProc:
  AllowMethodsWithArguments: true
Style/SwapValues:
  Enabled: true
