---
AllCops:
    Exclude:
        - 'node_modules/**/*'
        - 'tmp/**/*'
        - 'vendor/**/*'
        - '.git/**/*'
        - 'db/schema.rb'
        - 'bin/rails'
        - 'bin/rake'
        - '**/*.rake'
        - 'storage/**/*'
        - '**/shims/**'
        - '**.py'
    NewCops: enable

Layout/EndOfLine:
    EnforcedStyle: lf
Layout/EmptyLinesAroundAttributeAccessor:
    Enabled: true
Layout/SpaceAroundMethodCallOperator:
    Enabled: true
Lint/DeprecatedOpenSSLConstant:
    Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateElsifCondition:
    Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/MixedRegexpCaptureTypes:
    Enabled: true
Lint/MissingSuper:
    Exclude:
        - 'lib/creds.rb'
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
    Enabled: true
Lint/PercentStringArray:
    Exclude:
        - 'config/initializers/secure_headers.rb'
Lint/RaiseException:
    Enabled: true
Lint/StructNewOverride:
    Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
    Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
    Enabled: true
Metrics/AbcSize:
    Enabled: false
Metrics/ClassLength:
  Exclude:
    - "test/*/*"
Metrics/MethodLength:
    Enabled: false
Metrics/BlockLength:
    Exclude:
        - 'config/initializers/secure_headers.rb'
Style/AccessorGrouping:
    Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
    Enabled: true
Style/ArrayCoercion:
    Enabled: true
Style/BisectedAttrAccessor:
    Enabled: true
Style/CaseLikeIf:
    Enabled: true
Style/CollectionCompact: # (new in 1.2)
    Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
    Enabled: true
Style/ExponentialNotation:
    Enabled: true
Style/HashAsLastArrayItem:
    Enabled: true
Style/HashLikeCase:
    Enabled: true
Style/HashEachMethods:
    Enabled: true
Style/HashTransformKeys:
    Enabled: true
Style/HashTransformValues:
    Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
    Enabled: true
Style/NilLambda: # (new in 1.3)
    Enabled: true
Style/RedundantAssignment:
    Enabled: true
Style/RedundantFetchBlock:
    Enabled: true
Style/RedundantFileExtensionInRequire:
    Enabled: true
Style/RedundantRegexpCharacterClass:
    Enabled: true
Style/RedundantRegexpEscape:
    Enabled: true
Style/RescueStandardError:
    Exclude:
        - 'app/controllers/graphql_controller.rb'
Style/SlicingWithRange:
    Enabled: true
Style/SwapValues: # (new in 1.1)
    Enabled: true
